#!/usr/bin/with-contenv bash

# replace this file with custom install script on child images

# permissions
chown -R alpine:alpine /config/www

# make our folders
mkdir -p \
	/config/{php,log/php} \

touch /run/php-fpm.sock


# fix timezone in php.ini
sed -i "s#;date.timezone =.*#date.timezone = $TZ#g" /etc/php7/php.ini
#fix php-fpm log location
sed -i "s#;error_log = log/php7/error.log.*#error_log = /config/log/php/error.log#g" /etc/php7/php-fpm.conf
#fix php-fpm user
sed -i "s#user = nobody.*#user = alpine#g" /etc/php7/php-fpm.d/www.conf
sed -i "s#group = nobody.*#group = alpine#g" /etc/php7/php-fpm.d/www.conf

sed -i "s#listen = 127.0.0.1:9000#listen = /run/php-fpm.sock#g" /etc/php7/php-fpm.d/www.conf

sed -i "s#;listen.owner = nobody.*#listen.owner = alpine#g" /etc/php7/php-fpm.d/www.conf
sed -i "s#;listen.group = nobody.*#listen.group = alpine#g" /etc/php7/php-fpm.d/www.conf
sed -i "s#;listen.mode = 0660.*#listen.mode = 0660#g" /etc/php7/php-fpm.d/www.conf

# fix request terminate timeout
# sed -i "s#;request_terminate_timeout = 0#request_terminate_timeout = 30s#g" /etc/php7/php-fpm.d/www.conf

curl -o ${COCKPIT_SRC} -SL "https://github.com/agentejo/cockpit/archive/${COCKPIT_VERSION}.zip" \
    && unzip -q ${COCKPIT_SRC} -d /opt \
    && mv /opt/cockpit-0.8.11/* /config/www

# permissions
chown -R alpine:alpine \
	/config \
	/run \
	/var/lib/nginx

chmod -R g+w \
	/config/{nginx,www,log}

chmod -R 644 /etc/logrotate.d /config/log